openapi: 3.0.0
info:
  title: Discovery Service
  version: "0.0.0"
tags:
  - name: Discovery Service
    description: APIs for Decentralized Identifiers
servers:
  - url: https://vc.transmute.world
    description: Transmute Demo Server

paths:
  /.well-known/did-configuration.json:
    get:
      tags:
        - Discovery Service
      summary: Get Domain Linked Decentralized Identifiers
      operationId: getDidConfiguration
      description: Gets the well known did configuration for the api.
      responses:
        "200":
          description: Linked Identifiers
        "400":
          description: Client Error
        "500":
          description: Server Error
