openapi: 3.0.0
info:
  title: Holder Service
  version: "0.0.3-unstable"
tags:
  - name: Holder Service
    description: APIs for deriving and presenting credentials
paths:
  /credentials/derive:
    post:
      tags:
        - Holder Service
      summary: Derives a credential and returns it in the response body.
      operationId: deriveCredential
      description: Derives a credential and returns it in the response body.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Parameters for deriving the credential.
              properties:
                verifiableCredential:
                  $ref: "./components/VerifiableCredential.yml"
                frame:
                  $ref: "./components/Frame.yml"
                options:
                  type: object
                  additionalProperties: false
                  description: Options for specifying how the derived credential is created.
                  properties:
                    nonce:
                      type: string
                      description: An encoded nonce provided by the holder of the credential to be included into the LinkedDataProof.
                  example:
                    {
                      "nonce": "lEixQKDQvRecCifKl789TQj+Ii6YWDLSwn3AxR0VpPJ1QV5htod/0VCchVf1zVM0y2E=",
                    }

      responses:
        "201":
          description: Credential derived successfully.
          content:
            application/json:
              schema:
                $ref: "./components/VerifiableCredential.yml"
        "400":
          description: Invalid Request
        "500":
          description: Internal Error
        "501":
          description: Not Implemented
  /presentations/prove:
    post:
      tags:
        - Holder Service
      summary: Proves a presentation and returns it in the response body.
      operationId: provePresentation
      description: Proves a presentation and returns it in the response body.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                presentation:
                  $ref: "./components/Presentation.yml"
                options:
                  $ref: "./components/PresentationOptions.yml"
        description: Parameters for proving the presentation.
      responses:
        "201":
          description: Presentation successfully proved!
          content:
            application/json:
              schema:
                $ref: "./components/VerifiablePresentation.yml"
        "400":
          description: invalid input!
        "500":
          description: error!
