openapi: 3.0.0
info:
  title: Verifier Service
  version: "0.0.3-unstable"
  tags:
    - name: Verifier Service
      description: APIs for verifying credentials and presentations

servers:
  - url: https://vc.transmute.world/next/
    description: Transmute Demo Server
paths:
  /credentials/verify:
    post:
      tags:
        - Verifier Service
      summary: Verifies a credential
      operationId: verifyCredential
      requestBody:
        description: Parameters for verifying a verifiableCredential.
        content:
          application/json:
            schema:
              type: object
              properties:
                verifiableCredential:
                  $ref: "./components/VerifiableCredential.yml"
                options:
                  type: object
                  properties:
                    checks:
                      type: array
                      example: ["proof", "credentialStatus"]
      responses:
        "200":
          description: Verifiable Credential successfully verified!
          content:
            application/json:
              schema:
                $ref: "./components/VerificationResult.yml"
        "400":
          description: invalid input!
        "500":
          description: error!
  /presentations/verify:
    post:
      tags:
        - Verifier Service
      summary: Verifies a presentation
      operationId: verifyPresentation
      requestBody:
        description: Parameters for verifying a verifiablePresentation.
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    presentation:
                      $ref: "./components/VerifiablePresentation.yml"
                    options:
                      type: object
                      domain:
                        type: string
                        description: The domain for the presentation
                      challenge:
                        type: string
                        description: The challenge for the presentation
                      example: { "domain": "example.com", "challenge": "123" }
                - type: object
                  properties:
                    presentation:
                      $ref: "./components/Presentation.yml"
      responses:
        "200":
          description: Verifiable Presentation successfully verified!
          content:
            application/json:
              schema:
                $ref: "./components/VerificationResult.yml"
        "400":
          description: Invalid or malformed input
        "413":
          description: Payload too large
        "429":
          description: Request rate limit exceeded.
        "500":
          description: Internal Server Error
