get:
  summary: API Configuration
  operationId: getTraceabilityAPIConfiguration

  tags:
    - Discovery
  security: []
  responses:
    "200":
      description: Expected response to a valid request
      content:
        application/json:
          schema:
            $ref: "../schemas/TraceabilityAPIDIDWebDocument.yml"
    default:
      $ref: "../responses/UnexpectedError.yml"
